/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import miscelania.fondo2;
import tipografias.Fuentes;
import Clases.Clase;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author dark_
 */
public class JUEGO extends javax.swing.JInternalFrame {

    
    private final Fuentes tipoFuente; // para llamar el metodo de tipografias personalizadas
    ArrayList<String> vulgares      = new ArrayList();
    ArrayList<String> cientificos   = new ArrayList();
    ArrayList<String> fotos         = new ArrayList();
    /**
     * Creates new form JUEGO
     */
    public JUEGO() {
        initComponents();
        
        // SE PERSONALIZA TODO EL TEXTO CON FUENTES DEL PAQUETE TIPOGRAFIA
        tipoFuente = new Fuentes(); // crea tipo de fuente para usar atributos y procedimientos
        ///----------------///----- ARRAYLIST -----///---------------///

        ///----------------///----- ETIQUETAS -----///---------------///
        etiq_titulo_.setFont(tipoFuente.fuente(tipoFuente.GOD,0,24));
        etiq_letra_.setFont(tipoFuente.fuente(tipoFuente.GOD,0,24));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiq_imagenAve_ = new javax.swing.JLabel();
        etiq_titulo_ = new javax.swing.JLabel();
        etiq_vulgar_ = new javax.swing.JLabel();
        etiq_letra_ = new javax.swing.JLabel();
        txt_letra_ = new javax.swing.JTextField();
        btn_enter_ = new javax.swing.JToggleButton();
        etiq_cientifico_ = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        etiq_imagenAve_.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        etiq_titulo_.setText("AHORCADO");

        etiq_vulgar_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiq_vulgar_.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 51, 0), new java.awt.Color(255, 153, 51)));
        etiq_vulgar_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        etiq_letra_.setText("LETRA:");

        btn_enter_.setBackground(new java.awt.Color(51, 51, 255));
        btn_enter_.setForeground(new java.awt.Color(255, 255, 255));
        btn_enter_.setText("Enter");

        etiq_cientifico_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiq_cientifico_.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 51, 0), new java.awt.Color(255, 153, 51)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(etiq_titulo_))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiq_imagenAve_, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiq_letra_)
                        .addGap(44, 44, 44)
                        .addComponent(txt_letra_, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btn_enter_))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiq_cientifico_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiq_vulgar_, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiq_titulo_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiq_imagenAve_, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiq_vulgar_, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiq_cientifico_, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_letra_)
                    .addComponent(txt_letra_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enter_))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        cerrar();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        fondo2 f = new fondo2("/imagenes/fondo2.jpg"); // crea instancia objeto fondo y envia direccion de la imagen a usar
        this.add(f,BorderLayout.CENTER); // cuando la ventana sea abierta lo pinta con la imagen
        f.repaint(); // ejecuta la accion de colocar fondo al jframe
        iniciar();
    }//GEN-LAST:event_formInternalFrameOpened

    /////////// -- FUNCIONES O PROCEDIMIENTOS  -- ///////
    
    private void iniciar(){
        
        Clase c = new Clase();
        String respuesta;
        
        respuesta = c.importar();
        
        System.out.println("Respuesta importacion: "+respuesta);
        
        vulgares    = c.getVulgares();
        cientificos = c.getCientificos();
        fotos       = c.getFotos();
        
        etiq_vulgar_.setHorizontalTextPosition(SwingConstants.CENTER);
        etiq_cientifico_.setHorizontalTextPosition(SwingConstants.CENTER);
        
        etiq_vulgar_.setText( vulgares.get(0) );
        etiq_cientifico_.setText( cientificos.get(0) );
        etiq_imagenAve_.setIcon( new ImageIcon( fotos.get(0) ) );
        //JLabel1.setIcon(new ImageIcon(ruta));
        
    }
    
    private void cerrar(){ // para pedir confirmacion al cerrar una ventana
        
        Object [] opciones ={"Aceptar","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"En realidad desea realizar cerrar la aplicacion","Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION)
        {
            System.exit(0);// cierra totalmente la aplicacion
        }else{
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_enter_;
    private javax.swing.JLabel etiq_cientifico_;
    private javax.swing.JLabel etiq_imagenAve_;
    private javax.swing.JLabel etiq_letra_;
    private javax.swing.JLabel etiq_titulo_;
    private javax.swing.JLabel etiq_vulgar_;
    private javax.swing.JTextField txt_letra_;
    // End of variables declaration//GEN-END:variables
}
